export const defaultData = [
  {
    id: 148525,
    dateRemoved: "28 Oct 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "12 Jan 2022",
    link: "https://stackoverflow.com",
    source: "Stack Overflow",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "19 Jun 1998",
    link: "https://www.reddit.com/?rdt=49923",
    source: "Reddit",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "23 Sep 2023",
    link: "https://twitter.com",
    source: "Twitter",
    action: "Delisted",
  },
  {
    id: 458722,
    dateRemoved: "1 Nov 2022",
    link: "https://github.com",
    source: "Github",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "23 Sep 2023",
    link: "https://youtube.com",
    source: "YouTube",
    action: "Removed",
  },
  {
    id: 12243,
    dateRemoved: "19 May 2000",
    link: "https://facebook.com",
    source: "facebook",
    action: "Removed",
  },
  {
    id: 148525,
    dateRemoved: "28 Oct 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "12 Jan 2022",
    link: "https://stackoverflow.com",
    source: "Stack Overflow",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "19 Jun 1998",
    link: "https://www.reddit.com/?rdt=49923",
    source: "Reddit",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "23 Sep 2023",
    link: "https://twitter.com",
    source: "Twitter",
    action: "Delisted",
  },
  {
    id: 458722,
    dateRemoved: "1 Nov 2022",
    link: "https://github.com",
    source: "Github",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "23 Sep 2023",
    link: "https://youtube.com",
    source: "YouTube",
    action: "Removed",
  },
  {
    id: 12243,
    dateRemoved: "19 May 2000",
    link: "https://facebook.com",
    source: "facebook",
    action: "Removed",
  },
  {
    id: 148525,
    dateRemoved: "28 Oct 2023",
    link: "https://google.com",
    source: "Google",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "12 Jan 2022",
    link: "https://stackoverflow.com",
    source: "Stack Overflow",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "19 Jun 1998",
    link: "https://www.reddit.com/?rdt=49923",
    source: "Reddit",
    action: "Removed",
  },
  {
    id: 458722,
    dateRemoved: "23 Sep 2023",
    link: "https://twitter.com",
    source: "Twitter",
    action: "Delisted",
  },
  {
    id: 458722,
    dateRemoved: "1 Nov 2022",
    link: "https://github.com",
    source: "Github",
    action: "Delisted",
  },
  {
    id: 158476,
    dateRemoved: "23 Sep 2023",
    link: "https://youtube.com",
    source: "YouTube",
    action: "Removed",
  },
  {
    id: 12243,
    dateRemoved: "19 May 2000",
    link: "https://facebook.com",
    source: "facebook",
    action: "Removed",
  },
];
